### ISSUE TITLE
Uncaught Error: spawn "path\to\my\electronApp\...bin\youtube-dl" ENOENT 

### ISSUE THREAD

**Issue by sheunaluko** [przemyslawpluta/node-youtube-dl#107]
Hello.  I am using node-youtube-dl in an electron app that I built on ubuntu. On ubuntu everything is working fine. When I package the app for windows and tried to run it on my WINDOWS 10 machine I am getting the above error. 

Seems that it is not finding the file on Windows? 
I think it may have to do with the file extension missing for windows? Not sure though. What do you think?

Any help or insight would be much appreciated! Thank you

**Comment by puranjayjain** [comment]
@sheunaluko is your project open source? if yes please post the link i'll investigate it.
If you are using es6 (via babel) then try this: 
```
const fs = window.require('fs')
const youtubedl = window.require('youtube-dl')
```

**Comment by puranjayjain** [comment]
Update there is also the problem of some fs functions which need to be unpacked to make them work with electron see http://electron.atom.io/docs/all/#extra-unpacking-on-some-apis

**Comment by sheunaluko** [comment]
Thank you for getting back to me!

I'm away from my computer at the moment but will be back in stanford soon
and can check if this fixes the problem. I will let you know more within
the week.

-Shay

**Comment by puranjayjain** [comment]
**Another update:** I tried it again this time from the debugger it worked but it stills throws that error. @przemyslawpluta any help would be much appreciated

**Comment by puranjayjain** [comment]
@sheunaluko got it working! :smile: the child_process bug has been resolved. I think it is related to the fact that the path-to-the-exe is not correct according to electron. I tried manually to execute youtube-dl.exe using:

```
child_process.execFile(path.join(path.dirname(app.getAppPath()), './youtube-dl.exe'), ['https://www.youtube.com/watch?v=i3Jv9fNPjgk'], (err, stdout, stderr) => {
          if (err) throw err;
          console.log('inside')
          console.log(stdout, stderr)
        })
```

it worked but otherwise, it wouldn't so I think the problem is that the package would need to be tweaked a bit to accommodate electron and for that I guess we'll have to use a fork.

**Comment by sheunaluko** [comment]
Oh wow! That's so awesome man congratulations!

I am not a github expert, but you are saying you want to fork it and make
the changes... then use this new repository ?
Could you submit a pull request?

-Shay

**Comment by puranjayjain** [comment]
A PR would not be merged as it would be breaking the  existing package for non electron users through my solution.

**Comment by przemyslawpluta** [comment]
@puranjayjain drop PR and we'll have a look

**Comment by sheunaluko** [comment]
Oh right that makes sense !
So are you planning on making the fork ? and if so what will you name it ?

**Comment by puranjayjain** [comment]
@sheunaluko I'll just create a fork now and work on it and submit the pr. If merged its awesome ! if not I'll still keep the fork :)

**Comment by puranjayjain** [comment]
Update: After more testing I come to the final conclusion that there is absolutely no issue with this module. It works fine and more so, it is perfectly compatible with Electron (since it uses existsSync).
The only minor change I did to fix it is changing:
```
var execFile = require('child_process');
execFile(ytdlBinary, args, options, function done(err, stdout, stderr) 
```
to
```
var child_process = require('child_process');
child_process.execFile(ytdlBinary, args, options, function done(err, stdout, stderr) 
```

The problem is with the babel transpiler as it doesnt know that electron can handle require, and some minor es6 logic like, const, let, arrow functions, etc. and doesn't need to transpile that.

So it creates an issue when the code is transpiled.

I tried these changes and ran the code in the main process (app.js) it works.

But the same fails in renderer process (other script which is inside the actual loaded app) it fails with this error. So to solve that, I'll start a PR to change the above piece of code only as it doesn't affect others..

**Comment by puranjayjain** [comment]
There is another issue of the youtube-dl.exe not completely downloading (only 2- 4 mb) is downloaded.
I'm on node 6.1.0. and windows 10 (64)
I'll look to fix that in another PR.

**Comment by puranjayjain** [comment]
:tada: got it working see https://github.com/puranjayjain/youtube-dl-gui for poc

**Comment by sheunaluko** [comment]
Nice ! What is poc?
Do you know how I can apply the fix in my application?
Should I edit the node module or set some settings in babel .. ?

Thanks. I'll check out your youtube gui as well looks awesome !

-Shay

**Comment by puranjayjain** [comment]
Poc = proof of concept. Is your app open source, I can take a look at it. If not we can chat with me on gitter why pollute this issue thread?

**Comment by puranjayjain** [comment]
although its a bit late for a response, but take a look at nwjs for your app it will work perfectly without any hacks. you can also take a look at the polymer-test branch of my project i have a working example there.

**Comment by CanRau** [comment]
I'm trying to get it working using electron (1.7.8) electron-builder (19.27.3), tried in main and renderer process but am getting the same error as mentioned in the title running the app on windows 10, macOS works fine haven't tested linux so far...

do I have to download youtubedl.exe myself? but where exactly do I put it (next to electron.asar? but how?) and how to feed it to youtube-dl? 😃
