### ISSUE TITLE
Ok with transferring ownership?

### ISSUE THREAD

**Issue by fent** [przemyslawpluta/node-youtube-dl#140]
Hi @przemyslawpluta

Since I'm no longer actively maintaining this repo, and you are, are you ok with me transferring the ownership to you?

The repo would then be under your profile. And you'd have to update the npm package to point to the new url.

**Comment by przemyslawpluta** [comment]
Sounds good.

Regards,
Przemek

On 17 Feb 2017, at 13:42, Roly Fentanes <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @przemyslawpluta<https://github.com/przemyslawpluta>

Since I'm no longer actively maintaining this repo, and you are, are you ok with me transferring the ownership to you?

The repo would then be under your profile. And you'd have to update the npm package to point to the new url.

**Comment by przemyslawpluta** [comment]
@fent getting `Oops! That repository transfer has expired.` ... looks like you have to do it again.

**Comment by fent** [comment]
I reinitiated the transfer. It says it has to be accepted within 24 hrs or it expires.
