### ISSUE TITLE
wut

### ISSUE THREAD

**Issue by FireController1847** [przemyslawpluta/node-youtube-dl#146]
wut

```
8|Discedia | [Shard 2] { Error: Command failed: /root/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -x --audio-format mp3 http://www.youtube.com/watch?v=7bafv2jZ300
8|Discedia | ERROR: Signature extraction failed: Traceback (most recent call last):
8|Discedia |   File "/root/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
8|Discedia |     video_id, player_url, s
8|Discedia |   File "/root/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
8|Discedia |     raise ExtractorError('Cannot identify player %r' % player_url)
8|Discedia | ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
8|Discedia |  (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
8|Discedia |     at ChildProcess.exithandler (child_process.js:205:12)
8|Discedia |     at emitTwo (events.js:106:13)
8|Discedia |     at ChildProcess.emit (events.js:194:7)
8|Discedia |     at maybeClose (internal/child_process.js:899:16)
8|Discedia |     at Socket.<anonymous> (internal/child_process.js:342:11)
8|Discedia |     at emitOne (events.js:96:13)
8|Discedia |     at Socket.emit (events.js:191:7)
8|Discedia |     at Pipe._handle.close [as _onclose] (net.js:510:12)
8|Discedia |   killed: false,
8|Discedia |   code: 1,
8|Discedia |   signal: null,
8|Discedia |   cmd: '/root/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -x --audio-format mp3 http://www.youtube.com/watch?v=7bafv2jZ300' }
```
@fent

**Comment by itslukej** [comment]
`ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.` -> https://github.com/rg3/youtube-dl/issues/6410

Basically, update youtube-dl (check out scripts/download.js). 

Also.. for the love of god. Please don't use root.

**Comment by FireController1847** [comment]
I am updated to the latest version, sooo

**Comment by itslukej** [comment]
Note I said to update youtube-dl, not node-youtube-dl

**Comment by Armageddonas** [comment]
node-youtube-dl probably downloads the latest version of youtube-dl during `npm install`, you should reinstall it
This worked for me
```
npm remove youtube-dl
npm install youtube-dl
```
Thanks @itslukej

**Comment by Armageddonas** [comment]
**Well it seems specific urls are not working**
- https://www.youtube.com/watch?v=Z2Pa66C8Y1c
- http://www.youtube.com/watch?v=7bafv2jZ300 (mentioned by FireController1847)

**I get a similar error:**
Uncaught Error: Command failed: /home/konstantinos/development/projects/IdeaProjects/personal/mg-downloader/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=Z2Pa66C8Y1c
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/konstantinos/development/projects/IdeaProjects/personal/mg-downloader/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "/home/konstantinos/development/projects/IdeaProjects/personal/mg-downloader/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/konstantinos/development/projects/IdeaProjects/personal/mg-downloader/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "/home/konstantinos/development/projects/IdeaProjects/personal/mg-downloader/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/konstantinos/development/projects/IdeaProjects/personal/mg-downloader/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/konstantinos/development/projects/IdeaProjects/personal/mg-downloader/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'oE["do"](a,67)'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u'Unsupported JS expression u\'oE["do"](a,67)\'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


    at ChildProcess.exithandler (child_process.js:223)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:191)
    at maybeClose (internal/child_process.js:885)
    at Socket.<anonymous> (internal/child_process.js:334)
    at emitOne (events.js:96)
    at Socket.emit (events.js:188)
    at Pipe._handle.close [as _onclose] (net.js:501)

**Comment by itslukej** [comment]
@Armageddonas All the issues you get would likely come from youtube-dl, not node-youtube-dl, but i believe the issue you got has already been fixed, so an uninstall then install would sort it out

**Comment by Armageddonas** [comment]
@itslukej well indeed it was my mistake. After the update everything was ok, I forgot to post the answer here. Thanks again!

As I wrote before the simpliest way to update the `youtube-dl binary` is 
```
npm remove youtube-dl
npm install youtube-dl
```
