### ISSUE TITLE
how to download in higher res ?

### ISSUE THREAD

**Issue by TheNexusDesigns** [przemyslawpluta/node-youtube-dl#214]
all downloads are in 640x360 can we increase the resolution for yt downloads? if yes how, please ?

**Comment by Nolramado** [comment]
i don't speak spanish 
the problem is that high resolutions do not contain audio in the same url.
You have to get the url of the video in 720p or 1080p and apart the url the audio file 
then you must join the files with ffmpeg


`ytdl.getInfo()` 
from here you can extract the url of the video in mp4 and the url of the audio in m4a
I hope I could have helped you

**Comment by just1689** [comment]
Maybe there is a lib for combining these? Could make it easier to bring into this project

**Comment by just1689** [comment]
It looks like jdownload achieves this with ffmpeg. 

https://superuser.com/questions/277642/how-to-merge-audio-and-video-file-in-ffmpeg

**Comment by Kikobeats** [comment]
Same thing than https://github.com/przemyslawpluta/node-youtube-dl/issues/231.

If you found the answer, please consider making a PR for adding it into the README and beneficiate the rest of users 🙂
