### ISSUE TITLE
Downloads fail with HTTP 416 due to incorrect Range header on ^3.0.0

### ISSUE THREAD

**Issue by cdhowie** [przemyslawpluta/node-youtube-dl#290]
Commit 4bd8904 added the Range header for every request. I'm not sure the rationale for this change, since "the whole file" is implied if this header is missing. Regardless of the rationale, this change includes a fencepost error and therefore causes all downloads I have tried to fail with HTTP 416 (range not satisfiable).

```js
headers.Range = 'bytes=0-' + item.filesize
```

This should be:

```js
headers.Range = 'bytes=0-' + (item.filesize - 1)
```

My suggestion would be to simply revert this change as I can't see a reason why it was necessary to begin with.

**Comment by Kikobeats** [comment]
The thing is all tests are passing on green. 

Can you add a test reproducing this issue?

**Comment by Kikobeats** [comment]
cc @fredericgermain

**Comment by fredericgermain** [comment]
Hi!

I made the patch because the youtube server is much slower on audio without this. I have no idea why. You could check by yourself by checking duration of `npm run test` on 871382feeb2cf0e9c4f81560914a6892b1914a49 & 4bd8904f6f1ca50aa8cc1ca5717ba213e187dd7f.
See https://github.com/przemyslawpluta/node-youtube-dl/pull/285 for more details.

I'd thought I read semewhere the second range number should be excluded, like on Array.slice... But it seems your right on the `(item.filesize - 1)`.

Can you tell which URL you're trying to download? Maybe we can add it to the test.

**Comment by fredericgermain** [comment]
@cdhowie ?

**Comment by Kikobeats** [comment]
Closed until the original author provides more information – Thanks for your time checking this @fredericgermain 🙂

**Comment by RafaelKr** [comment]
Hi, this is a video which is failing with error 416 for me:
https://www.youtube.com/watch?v=hiT4Q1ntvzg

**Comment by RafaelKr** [comment]
I just tracked this issue down and found that filesize can be null.

It's also `null` when I run the command directly:
`youtube-dl --dump-json -f best http://www.youtube.com/watch?v=hiT4Q1ntvzg | jq`

I'll do a PR.

**Comment by Kikobeats** [comment]
@RafaelKr Yes please, make a PR!

Also, add the video url as part of the suite test 🙂

**Comment by RafaelKr** [comment]
https://github.com/przemyslawpluta/node-youtube-dl/pull/293
There you go! :)
